export const projects = [
  {
    title: 'Secret Agent',
    description: "Send our secret agent on a mission to find all the interesting details about a particular product by asin. Learn out how much they are selling, their current rank, the keywords they are ranking on, their revenue and many more.",
      image: '/images/1.png',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: 'Einstein Keyword',
    description: "See all the good and the bad sides of your listing. We will give you a suggestion of what needs to be a little bit better based on different criteria and how you can improve it so that your product listing becomes the best it can be.",
    image: '/images/4.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 1,
  },
  {
    title: 'Niche Analyzer',
    description: "Analyze your niche with the help of niche analyzer. Before entering a niche one must always see if it's the right one for his products. Detect all similar products and compare the price, rank, product vision and many more.",
    image: '/images/2.png',
    tags: ['React', 'JavaScript'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: 'Product Database',
    description: "Search easier in the Amazon product database. Discover all top sellers by category and various filters like rank, number of products, reviews, price of products and more. With the help of criteria searching you can easily spot the sellers you want to research.",
      image: '/images/3.jpg',
      tags: ['React', 'WebRTC'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },

  {
    title: 'Unichat',
    description: "Using React, Node.js, Express & MongoDB you'll learn how to build a Full Stack MERN Application - from start to finish. The App is called Memories and it is a simple social media app that allows users to post interesting events that happened in their lives.",
    image: '/images/4.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 4,
  },
  {
    title: 'Unichat',
    description: "Using React, Node.js, Express & MongoDB you'll learn how to build a Full Stack MERN Application - from start to finish. The App is called Memories and it is a simple social media app that allows users to post interesting events that happened in their lives.",
    image: '/images/4.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 5,
  },
  {
    title: 'Product Database',
    description: "Search easier in the Amazon product database. Discover all top sellers by category and various filters like rank, number of products, reviews, price of products and more. With the help of criteria searching you can easily spot the sellers you want to research.",
    image: '/images/3.jpg',
    tags: ['React', 'WebRTC'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },

  {
    title: 'Unichat',
    description: "Using React, Node.js, Express & MongoDB you'll learn how to build a Full Stack MERN Application - from start to finish. The App is called Memories and it is a simple social media app that allows users to post interesting events that happened in their lives.",
    image: '/images/4.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 4,
  },
  {
    title: 'Unichat',
    description: "Using React, Node.js, Express & MongoDB you'll learn how to build a Full Stack MERN Application - from start to finish. The App is called Memories and it is a simple social media app that allows users to post interesting events that happened in their lives.",
    image: '/images/4.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 5,
  },
];

export const pricing = [
  {
    title: 'Starter',
    price: '20$',
    time: '/ month',
    feature1: '',
    feature2: '',
    feature3: '',
    feature4: '',
    feature5: '',
    feature6: '',
    feature7: '',
    button: 'Free trial',
    id: 0,
  },
  {
    title: 'Advanced',
    price: '20$',
    time: '/ month',
    feature1: '',
    feature2: '',
    feature3: '',
    feature4: '',
    feature5: '',
    feature6: '',
    feature7: '',
    button: 'Free trial',
    id: 1,
  },
  {
    title: 'Professional',
    price: '20$',
    time: '/ month',
    feature1: '',
    feature2: '',
    feature3: '',
    feature4: '',
    feature5: '',
    feature6: '',
    feature7: '',
    button: 'Free trial',
    id: 2,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];
